development:
  aleph:
    aleph_base_url: http://rex.kb.dk/X
  dod_ebog_files:
    dod_server: webext-03
    user_name: valhal-reader
    password: 87E9XrfQ
    remote_path: /data1/e-mat/dod/
    download_path: /tmp
test:
  aleph:
    aleph_base_url: http://rex.kb.dk/X
  dod_ebog_files:
    dod_server: webext-03
    user_name: valhal-reader
    password: 87E9XrfQ
    remote_path: /data1/e-mat/dod/
    download_path: /tmp
production:
  aleph:
    aleph_base_url: http://rex.kb.dk/X
  dod_ebog_files:
    dod_server: webext-03
    user_name: valhal-reader
    password: 87E9XrfQ
    remote_path: /data1/e-mat/dod/
    download_path: /tmp
